service: cake-ordering-system
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  createOrder:
    handler: handler.createOrder
    events: 
      - http:
          path: /order
          method: post
resources:
  resources: 
    orderEventsStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: order-events
        ShardCount: 1
